version: "3.4"
services:
  watcher_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: omisego_dev
      POSTGRES_PASSWORD: omisego_dev
      POSTGRES_DB: omisego_dev
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U omisego_dev
      interval: 5s
      timeout: 3s
      retries: 5
  elixir-omg:
    build:
      context: .
      network: host
    environment:
      - DATABASE_URL=postgres://omisego_dev:omisego_dev@watcher_db:5432/omisego_dev
    image: omisegoimages/elixir-omg-tester:stable
    depends_on:
      - watcher_db
    links:
      - watcher_db
    volumes:
      - .:/home/elixir-user/elixir-omg
