version: "2.1"
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: omisego_dev
      POSTGRES_PASSWORD: omisego_dev
      POSTGRES_DB: omisego_dev
    healthcheck:
      test: pg_isready -U omisego_dev
      interval: 5s
      timeout: 3s
      retries: 5
  elixir-omg:
    build: .
    image: elixir-omg:dockercompose
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
