version: "3.4"
services:
  elixir-omg:
    environment:
      - DATABASE_URL=postgres://omisego_dev:omisego_dev@watcher_db:5432/omisego_dev
    image: omisegoimages/elixir-omg-tester:stable
    volumes:
      - .:/home/elixir-user/elixir-omg
