version: "2"
services:
  geth:
    image: ethereum/client-go:v1.8.20
    entrypoint: /bin/sh -c "geth --dev --dev.period 1 --rpc --rpcapi personal,web3,eth,net --rpcaddr 0.0.0.0 --rpcvhosts=* --rpcport=8545"
    ports:
     - "8545:8545"

  childchain_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: omisego_dev
      POSTGRES_PASSWORD: omisego_dev
      POSTGRES_DB: omisego_dev
    ports:
      - "5432:5432"

  watcher_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: omisego_dev
      POSTGRES_PASSWORD: omisego_dev
      POSTGRES_DB: omisego_dev
    ports:
      - "5433:5432"

  elixir-omg:
    build: .
    image: elixir-omg:dockercompose

  contractexchanger:
    image: jakebunce/contractexchanger:v0.0.1
    ports:
      - "5000:5000"
    depends_on:
      - "geth"

  childchain:
    image: elixir-omg:dockercompose
    entrypoint: /bin/bash -c "./launcher.py && mix xomg.child_chain.start --config ~/config.exs"
    environment:
      - MIX_ENV=dev
      - ELIXIR_SERVICE=CHILDCHAIN
      - CONTRACT_EXCHANGER_URL=http://localhost:5000
      - ETHEREUM_RPC_URL=http://localhost:8545
      - ETHEREUM_NETWORK=LOCALCHAIN
    restart: always
    ports:
      - "9656:9656"
    depends_on:
      - "contractexchanger"

  watcher:
    image: elixir-omg:dockercompose
    entrypoint: /bin/bash -c "./launcher.py && mix ecto.reset --no-start && mix xomg.watcher.start --config ~/config_watcher.exs"
    environment:
      - MIX_ENV=dev
      - ELIXIR_SERVICE=WATCHER
      - CONTRACT_EXCHANGER_URL=http://localhost:5000
      - ETHEREUM_RPC_URL=http://localhost:8545
      - CHILDCHAIN_URL=http://localhost:9656
      - ETHEREUM_NETWORK=LOCALCHAIN
      - DATABASE_URL=postgres://omisego_dev:omisego_dev@localhost:5432/omisego_dev
    restart: always
    ports:
      - "7434:7434"
      - "4000:4000"
    depends_on:
      - "childchain"

  ewallet:
    image: omisego/ewallet:latest
    entrypoint: /bin/bash -c "mix local.hex --force && mix local.rebar --force && mix do ecto.create, ecto.migrate && /init"
    environment:
      - DATABASE_URL=postgres://omisego_dev:omisego_dev@localhost:5433/omisego_dev 
      - LOCAL_LEDGER_DATABASE_URL=postgres://omisego_dev:omisego_dev@localhost:5432/omisego_dev
    restart: always
    ports: 
      - "4001:4000"
    depends_on:
      - "watcher_db"
