version: "3.7"

services:
  postgres:
    image: postgres:9.6.13-alpine
    restart: always
    environment:
      POSTGRES_USER: omisego_dev
      POSTGRES_PASSWORD: omisego_dev
      POSTGRES_DB: omisego_dev
    healthcheck:
      test: pg_isready -U omisego_dev
      interval: 5s
      timeout: 3s
      retries: 5
  omg-dev:
    build: .
    image: omg-dev-env:latest
    command: sh -c 'mv /build/* /app' && bash
    environment:
      DATABASE_URL: postgres://omisego_dev:omisego_dev@postgres:5432/omisego_dev
      MIX_ENV: dev
    depends_on:
      - postgres
    volumes:
      - ..:/app
    stdin_open: true
    tty: true

