openapi: 3.0.0
info:
  version: '1.0.0'
  title: Watcher's Informational API
  description: >
    API specification of the Watcher's Informational Service
    
    Error codes are available in **FIXME** [html](./errors), [json](./errors.json)
    and [yaml](./errors.yaml) formats.
  contact:
    name: OmiseGO
    email: omisego@omisego.co
  license:
    name: 'Apache 2.0: https://www.apache.org/licenses/LICENSE-2.0'
    url: 'https://omisego.network/'

tags:
  - name: Account
    description: Account related API.
  - name: Transaction
    description: Transaction related API.
  - name: Block
    description: Block related API.

paths:

requests:
responses:
definitions: